services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8181:8181"
    environment:
      - GO_ENV=development
    restart: unless-stopped
    networks:
      - records-go-network
    # Add healthcheck to ensure the application is running properly
#    healthcheck:
#      test: ["CMD", "wget", "-qO-", "http://localhost:8181/health"]
#      interval: 30s
#      timeout: 10s
#      retries: 3

  # Optional Redis service (uncomment if needed)
  # redis:
  #   image: redis:alpine
  #   ports:
  #     - "6379:6379"
  #   networks:
  #     - app-network
  #   volumes:
  #     - redis-data:/data
  #   restart: unless-stopped

networks:
  records-go-network:
    driver: bridge

# Uncomment if using Redis or other services that need persistent storage
# volumes:
#   redis-data: