services:
  records-api:
    container_name: records-api
    image: records:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7001:7001"
    environment:
      - RECORDS_API_PORT=7001
      - RECORDS_DB_CONNECTION=postgresql://postgres:Sup3rsecret1337@records-db:5432/records
    restart: unless-stopped
    networks:
      - records-network
    depends_on:
      records-db:
        condition: service_healthy

  records-db:
    container_name: records-db
    image: postgres:17
    ports:
      - "5479:5432"
    environment:
      - POSTGRES_PASSWORD=Sup3rsecret1337
    volumes:
      - records-db-data:/var/lib/postgresql/data
    networks:
      records-network:
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5


networks:
  records-network:

volumes:
  records-db-data:

