services:
  records-api:
    container_name: records-api
    image: records:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "0:7001"
    environment:
      - RECORDS_API_PORT=7001
    restart: unless-stopped
    networks:
      - records-network
    # Add healthcheck to ensure the application is running properly
#    healthcheck:
#      test: ["CMD", "wget", "-qO-", "http://localhost:8181/health"]
#      interval: 30s
#      timeout: 10s
#      retries: 3

  # Optional Redis service (uncomment if needed)
  # redis:
  #   image: redis:alpine
  #   ports:
  #     - "6379:6379"
  #   networks:
  #     - app-network
  #   volumes:
  #     - redis-data:/data
  #   restart: unless-stopped

networks:
  records-network:

# Uncomment if using Redis or other services that need persistent storage
# volumes:
#   redis-data: